[workspace]
members = [
    "hac-config",
    "hac-core",
    "hac-colors",
    "hac-index",
    "hac-cli",
]
resolver = "2"

[package]
name = "hac"
version.workspace = true
edition.workspace = true

[dependencies]
hac-index.workspace = true
tokio.workspace = true

anathema = { git = "https://github.com/togglebyte/anathema" }
itertools = "0.14.0"
eyre = "0.6.12"
color-eyre = "0.6.5"
crossterm = "0.29.0"

[workspace.metadata.crane]
name = "hac"

[workspace.package]
version = "0.2.0"
edition = "2024"

[workspace.dependencies]
hac-config = { path = "hac-config" }
hac-core = { path = "hac-core" }
hac-colors = { path = "hac-colors" }
hac-cli = { path = "hac-cli" }
hac-index = { path = "hac-index" }

anyhow = "1.0.81"
tokio = { version = "1.45.1", features = ["rt", "rt-multi-thread", "macros", "fs", "sync"] }
tracing = "0.1.40"
serde = { version = "1.0.204", features = ["derive", "rc"] }
serde_json = "1.0.124"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls-native-roots"] }
tree-sitter = "0.22.6"
tree-sitter-json = "0.21"
divan = "0.1.14"
lazy_static = "1.5"
