all: build test

build:
    cargo build

build-release:
    cargo build --release --verbose

test:
    cargo test --workspace

test-release:
    cargo test --workspace --release --verbose

coverage:
    cargo tarpaulin --verbose --workspace -o Html

build-time:
    cargo +nightly clean
    cargo +nightly build -Z timings

fmt:
    cargo fmt --check

lint:
    cargo clippy -- -D warnings

# =================================== #
#      RELEASE STUFF. DO NOT USE      #
# =================================== #

# uses convco to figure out the next version
new_version := "$(convco version --bump)"

release:
    git cliff -t "{{new_version}}" > CHANGELOG.md
    cargo check
    git checkout -b hac-release-v"{{new_version}}"
    git commit -asm "chore(release): release hac v{{new_version}}"
    git push --set-upstream origin hac-release-v"{{new_version}}"
    @echo "waiting 10 seconds so github catches up"
    sleep 10
    gh pr create --draft --title "chore: release hac v{{new_version}}" --body "This is an CI auto-generated PR" --reviewer wllfaria
    echo "generated release pull request successfully"

gh-release:
    git tag -d "v{{new_version}}" || echo "tag not found, creating"
    git tag --sign -a "v{{new_version}}" -m "auto generated by the justfile for eza v$(convco version)"
    mkdir -p ./target/"release-notes-$(convco version)"
    git cliff -t "v$(convco version)" --current > ./target/"release-notes-$(convco version)/RELEASE.md"
    git push origin "v{{new_version}}"
    gh release create "v$(convco version)" --target "$(git rev-parse HEAD)" --title "hac v$(convco version)" -d -F ./target/"release-notes-$(convco version)/RELEASE.md" ./target/"bin-$(convco version)"/*
