edition = "2021"
unstable_features = true
use_field_init_shorthand = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
format_code_in_doc_comments = true
reorder_impl_items = true
single_line_let_else_max_width = 100
single_line_if_else_max_width = 100
max_width = 120
