[package]
name = "hac-client"
version = "0.2.0"
edition = "2021"
description = "your handy API client, on your terminal!"
repository = "https://github.com/wllfaria/hac"
homepage = "https://github.com/wllfaria/hac"
documentation = "https://github.com/wllfaria/hac/wiki"
authors = ["Willians Faria <dev.willians.faria@gmail.com>"]
license = "MIT"
readme = "../README.md"
keywords = ["api", "api-client", "insomnia", "postman"]
categories = ["command-line-utilities"]
workspace = "../"

[dependencies]
hac-core.workspace = true
hac-config.workspace = true
hac-colors.workspace = true
hac-cli.workspace = true

anyhow.workspace = true
crossterm.workspace = true
tokio.workspace = true
tracing.workspace = true
reqwest.workspace = true
serde_json.workspace = true
ratatui.workspace = true
tree-sitter.workspace = true
divan.workspace = true
lazy_static.workspace = true

futures = "0.3.30"
tui-big-text = { version = "0.4.4" }
tracing-subscriber = { version = "0.3.18" }
tracing-appender = "0.2.3"
uuid = { version = "1.10.0", features = ["v4", "fast-rng", "macro-diagnostics"] }
rand = "0.8.5"

[dev-dependencies]
tempfile = "3.12.0"
mutants = "0.0.3"

[[bin]]
name = "hac"
test = false
bench = false
path = "src/main.rs"

[[bench]]
name = "collection_viewer_bench"
harness = false
