name: vhs
on:
  push:
    paths:
      - extra/tapes/*.tape

jobs:
  artifact-vhs:
    name: "Create VHS artifact"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: charmbracelet/vhs-action@v2

      - name: Create artifact
        run: extra/tapes/run_all.sh

      - name: Commit back changes
        run: |
          git add extra/*.gif
          git config --global user.name "vhs-action"
          git config --global user.email "actions@github.com"
          git commit -m "chore(ci): updated vhs tapes [skip ci]" || true
          git push
